version: '3.4'

services:
  nodinsoftprojectapi:
    container_name: WebApiContainer
    image: ${DOCKER_REGISTRY-}nodinsoftprojectapi
    build:
      context: .
      dockerfile: NodinSoftProjectAPI/Dockerfile
    depends_on:
            - SqlServerDb
    ports:
            - 8001:80 
  SqlServerDb:
    container_name: SqlServerContainer
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
            - 8002:1433
    environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=Aa12345678  